### ISSUE TITLE
What's the val set in RCAN training?

### ISSUE THREAD

**Issue by Senwang98** [yulunzhang/RCAN#107]
I am not sure the RCAN training process use which val set to train.
Set5/DIV2K?

**Comment by u0251077** [comment]
> I am not sure the RCAN training process use which val set to train.
> Set5/DIV2K?

Is DIV2K~
You can write this code in trainer.py (line:92) to check
```
tqdm.write(filename)
```

output:
```
Evaluation:
0801                                                                            
0802                                                                            
0803                                                                            
0804                                                                            
0805 
```

**Comment by Senwang98** [comment]
@u0251077 
Thanks for your reply.
I don't think these SR work use 801-805 as valset, they used benchamrk/Set5 as valset instead......
