### ISSUE TITLE
请教多通道问题

### ISSUE THREAD

**Issue by jianku122** [yulunzhang/RCAN#14]
您好，我想请教一下对图像不止rgb三个通道地输入您是怎么实现的，我在使用vgg时曾尝试六个通道因为‘’ValueError: 'arr' does not have a suitable array shape for any mode.‘’未成功，请问您是怎么解决scipy.misc.imsave对图像通道限制的局限的？

**Comment by yulunzhang** [comment]
您好，
不管输入的通道数是多少，都可以先转换成.pt或者.npy文件。
输出的通道数大于三时，可以在程序里面把网络输出保存为.mat文件，.npy应该也行，没试过。然后再用Matlab对保存的输出文件进行操作。
