### ISSUE TITLE
blurry SR image

### ISSUE THREAD

**Issue by XuecaiHu** [yulunzhang/RCAN#15]
The SR image generetaed by the released model is very blurry. What the reason? 
![img_001_srf_x4_sr](https://user-images.githubusercontent.com/19386212/48047114-f0d97e00-e1d1-11e8-95a5-3045d11ed486.png)
![img_002_srf_x4_sr](https://user-images.githubusercontent.com/19386212/48047115-f0d97e00-e1d1-11e8-8cb3-ed4bbd92bb37.png)

model ? or the input?

**Comment by XuecaiHu** [comment]
the test on the BIX2,BIX4,BIX3. The above images are generated by BIX4

**Comment by yulunzhang** [comment]
Hi,
Can you show me the test script you used? I think you didn’t use the provided test script.

**Comment by XuecaiHu** [comment]
yes, i change the data_test to be the B100. It seems that the benchmark.py not the myimage.py

**Comment by yulunzhang** [comment]
sure, just try the provided scripts first to make sure the basic flow (network, pre-trained model) work well. Then try to modify it according to your own purpose.

**Comment by XuecaiHu** [comment]
Yeah, thank you fora answer. If  I want to train your  RCAN from scratch，how many epoches should  i train the network ? 1000? 800? or 300? which is the best from your experiences

**Comment by yulunzhang** [comment]
1000 epochs

**Comment by XuecaiHu** [comment]
thanks~
