### ISSUE TITLE
Training a BD model

### ISSUE THREAD

**Issue by wxywhu** [yulunzhang/RCAN#17]
Hi, i want to train a BD model from the beginning, how can i get the LR data?
I found the operation of the BD in the Prepare_TestData_HR_LR.m, is this the same code you use to obtain the LR data? And if i get the LR data from BD, it seems that i should rename it "DIV2K_LR_bicubic" to make it train.

**Comment by yulunzhang** [comment]
Yes, you can use the operation of the BD in the Prepare_TestData_HR_LR.m to obtain LR training data.
 To train BD model, you only have to rename  "DIV2K_LR_bicubic" to other name, like  "DIV2K_LR_BD". Then modify Line 41 in RCAN_TrainCode/code/data/div2k.py to have the same LR folder name.
![image](https://user-images.githubusercontent.com/22829440/48207610-07511800-e33f-11e8-9416-ec86dd698dc1.png)

**Comment by wxywhu** [comment]
Thank you so much
