### ISSUE TITLE
unbelievable work

### ISSUE THREAD

**Issue by ABDOELSHEMY** [yulunzhang/RCAN#2]
hi @yulunzhang 
just want to thank you, for your stunning work, amazing  Super-Resolution result, from my heart thank you man.

**Comment by KunpengLi1994** [comment]
Cool! More great works are on the way :)

**Comment by ABDOELSHEMY** [comment]
@KunpengLi1994, much thanks for you and for all RCAN team for this great work, we really appreciate your work.

-

**Comment by tensorboy** [comment]
You set a high bar with this one!
