### ISSUE TITLE
Resuming training

### ISSUE THREAD

**Issue by sefibk** [yulunzhang/RCAN#26]
Hi,
I had a a technical problem during training and it got stuck after 800 epochs.
Is there a way to restart with the exact same parameters and have it continue plotting the log?

I tried '--resume -1' which loads the model but not the parameters and doesn't continue the log.
Is there an automatic way to do this?

Thank you

**Comment by yulunzhang** [comment]
Hi,
Use --load option to specify the pretrained folder, also set --resume as -1 to load the latest model from your pretrained folder. Then you can continue to train your previous model with correct base checkpoint and numbering.
