### ISSUE TITLE
训练1000个epoch大概需要几天？

### ISSUE THREAD

**Issue by Zamirquito** [yulunzhang/RCAN#28]
您好，感谢您提供源代码。
我现在正在尝试重新训练x4的模型，但我发现在一块1080ti上面跑一个epoch都需要很长时间，所以我想问一下重新训练1000个epoch大概需要多久呢？谢谢

**Comment by yulunzhang** [comment]
您好，
我用Titan Xp训练，X4倍，1个epoch大概818s，1000个epoch就大概是227小时（9天多）。时间是我根据Log，刚刚计算的。倍数上升，训练时间确实大大增加了。
![image](https://user-images.githubusercontent.com/22829440/50322165-ffd67000-04a1-11e9-8ff7-fd1f1c432759.png)

**Comment by Zamirquito** [comment]
好的，多谢。

**Comment by lxtGH** [comment]
你好！如果是用8卡或者4卡，速度会提升多少呢？？
