### ISSUE TITLE
Dropbox link give 404

### ISSUE THREAD

**Issue by Ruffi** [yulunzhang/RCAN#3]
Thanks for sharing your great work :)
I wanted to try to run it with the pre-trained model, but the dropbox link on RCAN/RCAN_TrainCode/experiment/model/Readme.md is returning a 404 status code

**Comment by yulunzhang** [comment]
Hi,
I updated the model links:
https://www.dropbox.com/s/qm9vc0p0w9i4s0n/models_ECCV2018RCAN.zip?dl=0
or 
https://pan.baidu.com/s/1bkoJKmdOcvLhOFXHVkFlKA
