### ISSUE TITLE
How can i get X8 LR Bic images?

### ISSUE THREAD

**Issue by zllrunning** [yulunzhang/RCAN#32]
Hello, how can i get X8 LR Bic images since DIV2K dataset only contains x2, x3 and x4 LR images?

**Comment by yulunzhang** [comment]
Hi,
Please use this function to get the LR images for x2/3/4/8 scaling factors.
https://github.com/yulunzhang/RCAN/blob/master/RCAN_TestCode/Prepare_TestData_HR_LR.m

**Comment by zllrunning** [comment]
Thanks!
