### ISSUE TITLE
about crop the dataset, mean is different

### ISSUE THREAD

**Issue by luxuriance19** [yulunzhang/RCAN#33]
hello, I cut the images into 48*48 patches, but I found out that the mean is 10^-2 order. The dataset I made is not the same with you. I can't find the details of the input processing, can you point out a way? Thanks very much.

**Comment by yulunzhang** [comment]
Hi,
If you're using the DIV2K dataset, just use the mean of DIV2K reported in the code. This mean value is not affected by the input patch size.

I didn't do any specific operations to process the input data. You can just follow the instructions in the github to reproduce the results in the paper. Thanks.

**Comment by luxuriance19** [comment]
Thanks, I am not familiar with pytorch, so I implemented in tensorflow, I use the mean in your code. but it turn out to degrade the model. So I calculate the mean of my dataset. Really weird thing happed. The first 10000 patches have the mean in 0.1 order, but when I calculate all the patches, it turned out to be 0.06***. I find the implementation in data, but I don't find the doing patches part. I find the .npy file. Sorry again, but can you please give me the instructions in details. Thanks very much.

**Comment by luxuriance19** [comment]
> Hi,
> If you're using the DIV2K dataset, just use the mean of DIV2K reported in the code. This mean value is not affected by the input patch size.
> 
> I didn't do any specific operations to process the input data. You can just follow the instructions in the github to reproduce the results in the paper. Thanks.

Follow the instructions, I crop one patch at a picture each epoch, then a epoch have 800 patches from the train pictures, but the network can't converge. I didn't implement it on pytorch. I did a tensorflow version. Did I get the wrong idea of the crop part? Thanks very much

**Comment by aatiqa-ghazali** [comment]
@luxuriance19 I am facing the same issue.How did you solve that issue?
