### ISSUE TITLE
Is there two errors about comparative images in this paper?

### ISSUE THREAD

**Issue by angleboy8** [yulunzhang/RCAN#43]
In Fig. 5, the last two images ocurs error. Others images are flipped up and down significantly.

**Comment by yulunzhang** [comment]
Hi
Fig5 has three groups of comparisons, could you point out which images exactly?

Also, all the results are reproduced by the public code and model. There’s no error in the results.

**Comment by angleboy8** [comment]
Hi, the last two groups occur error. You carefully look other eight comparative images except for HR and RCAN one.  Others images are flipped up and down significantly. Because of attaching images, I only describe two errors.

**Comment by yulunzhang** [comment]
Hi,
There's no error. Let's take img_073 in Fig5 as an example. The results of other 8 methods are correct and the exact outputs by their codes and models.
You can run the SR results with other methods to see whether they would produce such results or not. Thanks.

**Comment by angleboy8** [comment]
Please you pay more attention the texture direction of  fig. Bicubic and fig. RCAN in the last two groups. Obviously, test image and restoration image in this paper  are wrong.  If you need my help, I can send you a email that point out the detailed errors.

**Comment by yulunzhang** [comment]
Ok, please send me an email pointing out the error. yulun100@gmail.com
Thanks!

**Comment by angleboy8** [comment]
Please notice your email. I just now sent a email. Thank you!

**Comment by angleboy8** [comment]
Thank you for your reply. You're right. Indeed, other method exits some drawbacks that produce visual error for people's eyes, which results in my misunderstanding.  Thanks a lot again. Best wishes!

**Comment by angleboy8** [comment]
The latest version of Pytorch occurs the following error:

 The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.:

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...
