### ISSUE TITLE
Training with gray images

### ISSUE THREAD

**Issue by DanChen001** [yulunzhang/RCAN#44]
Hi, Thank you for sharing the code. Great work!

How can i train a model with gray training images?  Thanks.

**Comment by yulunzhang** [comment]
Hi,

You can refer to our newly released code about gray-scale image denoising, which is the case for single channel training data.
https://github.com/yulunzhang/RNAN/tree/master/DN_Gray

**Comment by DanChen001** [comment]
> Hi,
> 
> You can refer to our newly released code about gray-scale image denoising, which is the case for single channel training data.
> https://github.com/yulunzhang/RNAN/tree/master/DN_Gray

Thanks
