### ISSUE TITLE
about nn.AdaptiveAvgPool2d

### ISSUE THREAD

**Issue by lz666win** [yulunzhang/RCAN#45]
you use nn.AdaptiveAvgPool2d when you define CALayer in rcan.py,but you use AdaptiveAvgPool2d(1),as i know,when the pool size =1,this pooling is no difference with AvgPool2d(1),and it change nothing with input,so i want to know what dose it mean in your network,thank you!

**Comment by yulunzhang** [comment]
Hi
I think you can read the document about the used global average pooling operation or just run&debug the code. Then, you should see the difference against what you expected. Thanks!
