### ISSUE TITLE
您好，请问您写论文时候的网络结构图是怎么画的呢

### ISSUE THREAD

**Issue by CodeforL** [yulunzhang/RCAN#47]
我用visio画出来的图像质量很低

**Comment by CodeforL** [comment]
请教下

**Comment by yulunzhang** [comment]
你好，
你可能是保存成了图片格式。
我一般用PPT画网络结构图，用matlab画一些训练过程的曲线图，然后，保存为PDF或者eps等矢量图格式。绝大部分情况下，没必要用viso。
