### ISSUE TITLE
Pre-trained ddbpn, edsr, mdsr Models Available? 

### ISSUE THREAD

**Issue by HenryJunW** [yulunzhang/RCAN#59]
Hello, impressive work. I am wondering whether the pre-trained other structures' models are available or not. Thanks.

**Comment by yulun** [comment]
Hi,
EDSR,MDSR pretrained models are available at https://github.com/thstkdgus35/EDSR-PyTorch, specifically, https://cv.snu.ac.kr/research/EDSR/model_pytorch.tar

For ddbpn, you can find them at https://github.com/alterzero/DBPN-Pytorch

**Comment by yulunzhang** [comment]
Hi,
EDSR,MDSR pretrained models are available at https://github.com/thstkdgus35/EDSR-PyTorch, specifically, https://cv.snu.ac.kr/research/EDSR/model_pytorch.tar

For ddbpn, you can find them at https://github.com/alterzero/DBPN-Pytorch
