### ISSUE TITLE
Training epochs

### ISSUE THREAD

**Issue by adaxidedakaonang** [yulunzhang/RCAN#6]
Hi, I recently read your paper, and want to ask you a question.
You don't write total training epochs in your paper, so I find it in your code. The option.py writes '--epochs 1000', which means all the models trained for 1000 epochs?

**Comment by yulunzhang** [comment]
All the results for (BI x2, x3, x4, x8) in the ECCV paper are achieved within 1000 epochs (In fact, I didn't select models and just used the models at about 1000th epoch to produce the results for paper). For BD model, I used about 30 epochs based on BI model. Anyway, no matter training from scratch or fine-tuning models, 1000 epochs are enough to obtain the results in the paper.

**Comment by adaxidedakaonang** [comment]
Oh, I see it. Thanks for your reply.
