### ISSUE TITLE
I have a question about RCAN.

### ISSUE THREAD

**Issue by Woosuk-Kim** [yulunzhang/RCAN#63]
I have a question about channel in RCAN.
Also, I sent the following contents by e-mail.

I am interested in Super Resolution and I am studying various models.
In addition, have trained and tested using the RCAN code you posted on github.

But I do not know why SR models use 64 channels.

In the SRCNN paper, 64 channels out of 128, 64, and 32 channels seem to be the most reasonable.
But I'm not sure that 64 channels are the most common.

Could you kindly tell us the reason why have 64 channels in RCAN?
Or is there a theoretical or experimental reason for SR models to use 64 channels?

I look forward to hearing from you.

Thank you.

**Comment by yulunzhang** [comment]
Hi 김우석,

The performance of a network depends largely on the number of parameter. Network depth and width can directly affect the network parameter number. In general, deeper and wider network would achieve better results. On the other hand, the success of ResNet tells us that we don't have to manually and carefully design the channel number of each Conv layer, as did in SRCNN. Instead, we can just keep the same channel number in most Conv layers.

Then, in image SR, 64 channel number in each Conv layer has been a common practice, as it achieves good tradeoff among the parameter number, training time, and performance. Most SR methods follow this setting. To keep fair comparison, we just use 64 channel in RCAN. Of course, we can use larger channel number and would achieve better results. But, it would be unfair for other methods.

Hope this helps you. If you have any questions, please let me know.
