### ISSUE TITLE
PNSR not improving by using pre-trained models

### ISSUE THREAD

**Issue by arun121cs** [yulunzhang/RCAN#7]
The output i am getting after running the test scripts is this
(deeplearning) administrator@administrator-System-Product-Name:~/Desktop/Projects/RCAN/RCAN_TestCode/code$ python main.py --data_test MyImage --scale 3 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX3.pt --test_only --save_results --chop --save 'RCAN' --testpath /home/administrator/Desktop/Projects/RCAN/RCAN_TestCode/LR/LRBI --degradation BD --testset Set5
Making model...
Use DIV2K mean (0.4488, 0.4371, 0.4040)
Loading model from ../model/RCAN_BIX3.pt

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:02<00:00,  1.72it/s]
[MyImage x3]	PSNR: 0.000 (Best: 0.000 @epoch 1)
Total time: 2.90s, ave time: 0.58s

I have downloaded the pre-trained models. I have used Set5 data which is present in LR folder.

**Comment by yulunzhang** [comment]
please use '--degradation BI'

**Comment by arun121cs** [comment]
(deeplearning) administrator@administrator-System-Product-Name:~/Desktop/Projects/RCAN/RCAN_TestCode/code$ python main.py --data_test MyImage --scale 8 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX8.pt --test_only --save_results --chop --self_ensemble --save 'RCANplus' --testpath /home/administrator/Desktop/Projects/RCAN/RCAN_TestCode/LR/LRBI --degradation BD  --testset Set5
Making model...
Use DIV2K mean (0.4488, 0.4371, 0.4040)
Loading model from ../model/RCAN_BIX8.pt

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:49<00:00,  9.91s/it]
[MyImage x8]	PSNR: 0.000 (Best: 0.000 @epoch 1)
Total time: 49.54s, ave time: 9.91s

I am getting better resolution images. It is just it is showing 0000 value of PSNR. Is it normal or there is something wrong?

**Comment by arun121cs** [comment]
Please also tell what is the role of degradation BD. There is not much mentioned regarding this in readme.

**Comment by yulunzhang** [comment]
When we feed LR images to the network, we don't have the HR image as reference. So, we cannot calculate PSNR in the code and just set it as 0. To obtain correct PSNR values, please use matlab script, groud truth images, and our upscaled images to calculate thems. I clarified those details in the readme.

In the readme, I've shown that:
```bash
# BI degradation model, X2, X3, X4, X8
# RCAN_BIX2
python main.py --data_test MyImage --scale 2 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX2.pt --test_only --save_results --chop --save 'RCAN' --testpath /media/yulun/Disk10T/datasets/super-resolution/LRBI --testset Set5
# RCAN_BIX3
python main.py --data_test MyImage --scale 3 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX3.pt --test_only --save_results --chop --save 'RCAN' --testpath /media/yulun/Disk10T/datasets/super-resolution/LRBI --testset Set5
# RCAN_BIX4
python main.py --data_test MyImage --scale 4 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX4.pt --test_only --save_results --chop --save 'RCAN' --testpath /media/yulun/Disk10T/datasets/super-resolution/LRBI --testset Set5
# RCAN_BIX8
python main.py --data_test MyImage --scale 8 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX8.pt --test_only --save_results --chop --save 'RCAN' --testpath /media/yulun/Disk10T/datasets/super-resolution/LRBI --testset Set5
# BD degradation model, X3
# RCAN_BDX3
python main.py --data_test MyImage --scale 3 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BDX3.pt --test_only --save_results --chop --save 'RCAN' --testpath /media/yulun/Disk10T/datasets/super-resolution/LRBD --degradation BD --testset Set5
```
'--degradation BI' is for BI model.  '--degradation BD' is for BD model. I set them for easier file naming. These two degradation models are clearified in our paper.
