### ISSUE TITLE
测试的时候提示被除数为0

### ISSUE THREAD

**Issue by zsommer** [yulunzhang/RCAN#77]
(pytorch) D:\RCAN-master\RCAN_TestCode\code>python main.py --data_test MyImage --scale 2 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX2.pt --test_only --save_results --chop --save 'RCAN' --testpath ../LR/LRBI --testset Set5
Making model...
Use DIV2K mean (0.4488, 0.4371, 0.4040)
Loading model from ../model/RCAN_BIX2.pt

Evaluation:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    while not t.terminate():
  File "D:\RCAN-master\RCAN_TestCode\code\trainer.py", line 139, in terminate
    self.test()
  File "D:\RCAN-master\RCAN_TestCode\code\trainer.py", line 111, in test
    self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test)
ZeroDivisionError: division by zero

请问这是什么原因，。。。

**Comment by zsommer** [comment]
检查过测试图片路径，图片格式都没有问题，是没有加载到LR文件夹里的测试图片吗

**Comment by sjscotti** [comment]
I am having the same "division by zero" problem.  I have implemented the fix in https://github.com/yulunzhang/RCAN/issues/30#issue-394928993 to get rid of the error iof Incompatible version with pytorch 1.0 #30 
I am running on google colab using torch 1.0.1 and  torchvision-0.2.2.post3

**Comment by yulunzhang** [comment]
> (pytorch) D:\RCAN-master\RCAN_TestCode\code>python main.py --data_test MyImage --scale 2 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX2.pt --test_only --save_results --chop --save 'RCAN' --testpath ../LR/LRBI --testset Set5
> Making model...
> Use DIV2K mean (0.4488, 0.4371, 0.4040)
> Loading model from ../model/RCAN_BIX2.pt
> 
> Evaluation:
> 0it [00:00, ?it/s]
> Traceback (most recent call last):
> File "main.py", line 18, in
> while not t.terminate():
> File "D:\RCAN-master\RCAN_TestCode\code\trainer.py", line 139, in terminate
> self.test()
> File "D:\RCAN-master\RCAN_TestCode\code\trainer.py", line 111, in test
> self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test)
> ZeroDivisionError: division by zero
> 
> 请问这是什么原因，。。。

misc.imread or misc.imsave are not available in the newer version of scipy. Instead, try to use imageio.imread or imageio.imsave.
