### ISSUE TITLE
Pre-trained Model link not working

### ISSUE THREAD

**Issue by farazBhatti** [yulunzhang/RCAN#87]
@yulunzhang Hi, can the link of pre-trained model be updated as it is not working. Was hoping to run inference using it and see results. Thanks.

![Screenshot from 2019-11-11 16-44-31](https://user-images.githubusercontent.com/37732181/68585111-1bc07700-04a3-11ea-8e5f-0fadcbba71f8.jpg)

**Comment by yulunzhang** [comment]
Hi,
All the models (BIX2/3/4/8, BDX3) can be downloaded from [Dropbox](https://www.dropbox.com/s/qm9vc0p0w9i4s0n/models_ECCV2018RCAN.zip?dl=0), [BaiduYun](https://pan.baidu.com/s/1bkoJKmdOcvLhOFXHVkFlKA), or [GoogleDrive](https://drive.google.com/file/d/10bEK-NxVtOS9-XSeyOZyaRmxUTX3iIRa/view?usp=sharing).
