### ISSUE TITLE
Run model on a single test image

### ISSUE THREAD

**Issue by owoshch** [yulunzhang/RCAN#9]
Hi,
Thank you for your research! 

I was wondering which script can I use to apply pretrained model for particular image instead of  applying it for full test5 set?

**Comment by yulunzhang** [comment]
Hi,
Suppose you have an image (**test.png**) and want to super-resolve it with scaling factor **x2** (for x3, x4, x8, same way).
The easiest way without modifying the code can be done as follows:
1.make directory: RCAN_TestCode/LR/LRBI/Demo/x2/
2.put your LR image in the above directory: RCAN_TestCode/LR/LRBI/Demo/x2/test.png
3.cd to RCAN_TestCode/code, run the following script
```
python main.py --data_test MyImage --scale 2 --model RCAN --n_resgroups 10 --n_resblocks 20 --n_feats 64 --pre_train ../model/RCAN_BIX2.pt --test_only --save_results --chop --save 'RCAN' --testpath ../LR/LRBI --testset Demo
```
Your result will be in RCAN_TestCode/SR/BI/RCAN/Demo/x2/test.png

**Comment by Lane565** [comment]
I use windows10 and pytorch1.1.0 and followed your steps, but I got results like this:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "E:\xiang\Super-resolution\RCAN-master\RCAN_TestCode\code\data\__init__.py", line 3, in <module>
    from dataloader import MSDataLoader
  File "E:\xiang\Super-resolution\RCAN-master\RCAN_TestCode\code\dataloader.py", line 17, in <module>
    from torch.utils.data.dataloader import _worker_manager_loop
ImportError: cannot import name '_worker_manager_loop'
