### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nmhkahn** [yulunzhang/RCAN#92]
Hi, what's the license of this code?
Thank you.

**Comment by yulunzhang** [comment]
Hi Namhyuk,

Thanks for your interest. The RCAN code is based on EDSR-PyTorch (https://github.com/thstkdgus35/EDSR-PyTorch).

In EDSR-PyTorch, the MIT license (https://github.com/thstkdgus35/EDSR-PyTorch/blob/master/LICENSE) is used. 

The credit should be given to EDSR-PyTorch, which also includes RCAN code. So, you can use the EDSR-PyTorch code and MIT license, which could be more official. Thanks.

**Comment by nmhkahn** [comment]
I got it. thanks!
